# Pipeline name
name: PR Verification

# Trigger for pull requests
pr:
  branches:
    include:
      - '*'

# Stages
stages:
- stage: PRVerification
  displayName: 'Pull Request Verification'
  jobs:
  - job: HelloWorldJob
    displayName: 'Hello World Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Hello World"
      displayName: 'Display Hello World'
