name: PR Verification

pr:
    branches:
        include:
            - '*'

stages:
    - stage: ScratchOrgTests
      displayName: 'Scratch Org Tests'
      dependsOn: FormattingAndLwcTests
      condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'dependabot[bot]'))
      jobs:
          - job: ScratchOrgTestsJob
            displayName: 'Scratch Org Tests Job'
            pool:
                vmImage: 'ubuntu-latest'
            steps:
                - script: npm install --location=global @salesforce/cli
                  displayName: 'Install Salesforce CLI'

                - script: |
                      echo "$(DEVHUB_SFDX_URL)" > DEVHUB_SFDX_URL.txt
                  displayName: 'Populate auth file with DEVHUB_SFDX_URL secret'

                - script: sf org login sfdx-url -f DEVHUB_SFDX_URL.txt -a devhub -d
                  displayName: 'Authenticate Dev Hub'

                - script: sf org create scratch -f config/project-scratch-def.json -a streaming-ci -d -y 1
                  displayName: 'Create scratch org'

                - script: sf project deploy start
                  displayName: 'Push source'

                - script: sf org assign permset -n Streaming_Monitor
                  displayName: 'Assign permission set'

                - script: sf apex test run -c -r human -d ./tests/apex -w 20
                  displayName: 'Run Apex tests'

                - script: sf org delete scratch -p -o streaming-ci
                  condition: always()
                  displayName: 'Delete scratch org'
