# Pipeline name
name: PR Verification

# Trigger for pull requests
pr:
  branches:
    include:
      - '*'

# Stages
stages:
- stage: PRVerification
  displayName: 'Pull Request Verification'
  jobs:
  - job: FormattingAndLwcTestsJob
    displayName: 'Formatting and LWC Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Install npm dependencies
    - script: npm ci
      displayName: 'Install npm dependencies'

    # Run Prettier formatting verification
    - script: npm run prettier:verify
      displayName: 'Run Prettier: Verify'

    # Run linting
    - script: npm run lint
      displayName: 'Run Linting'

    # Run unit tests with coverage
    - script: npm run test:coverage
      displayName: 'Run Unit Tests with Coverage'
