# Pipeline name
name: Create StreamingMonitor Unlocked Package Version

trigger:
    - master

variables:
    UAT_SFDX_URL: 'force://PlatformCLI::5Aep861fNsYAqFS2IVKU4L2ZnJ2ErA4OPjUIC5.uofHEc7YuMpkR5wxaGsMKrZfaT4lCo7CrJY82O74vXLRhWzN@young-life--uat.sandbox.my.salesforce.com' # Set in pipeline variables

# Stages
stages:
    - stage: CreatePackageVersion
      displayName: 'Create Salesforce Package Version'
      jobs:
          - job: CreateAndInstallPackage
            displayName: 'Create and Install Salesforce Package'
            pool:
                vmImage: 'ubuntu-latest'
            steps:
                - script: npm install --location=global @salesforce/cli
                  displayName: 'Install Salesforce CLI'

                - script: echo "$(DEVHUB_SFDX_URL)" > DEVHUB_SFDX_URL.txt
                  displayName: 'Populate auth file with DEVHUB_SFDX_URL secret'

                - script: sf org login sfdx-url -f DEVHUB_SFDX_URL.txt -a devhub -d
                  displayName: 'Authenticate Dev Hub'

                - script: |
                      PACKAGE_VERSION_ID=$(sf package version create --package "yl-smon" --wait 10 -v sfprod --installation-key-bypass --code-coverage --json | jq -r '.result.SubscriberPackageVersionId')
                      echo "##vso[task.setvariable variable=PACKAGE_VERSION_ID]$PACKAGE_VERSION_ID"
                  displayName: 'Create Package Version and Set Variable'

                - script: echo "$(UAT_SFDX_URL)" > UAT_SFDX_URL.txt
                  displayName: 'Populate auth file with DEVHUB_SFDX_URL secret'

                - script: sf org login sfdx-url -f UAT_SFDX_URL.txt -a UAT -d
                  displayName: 'Authenticate UAT'

                # Step 5: Install the package in UAT
                - script: |
                      sf package install --package "$(PACKAGE_VERSION_ID)" --target-org UAT --apex-compile package --publish-wait 10 -w 10
                  displayName: 'Install Package in UAT'
