# Pipeline name
name: Create StreamingMonitor Unlocked Package Version

trigger:
    - master

# Stages
stages:
    - stage: CreatePackageVersion
      displayName: 'Create Salesforce Package Version'
      jobs:
          - job: CreateAndInstallPackage
            displayName: 'Create and Install Salesforce Package'
            pool:
                vmImage: 'ubuntu-latest'
            steps:
                # Step 1: Install Salesforce CLI
                - script: npm install --location=global @salesforce/cli
                  displayName: 'Install Salesforce CLI'

                # Step 2: Authenticate with Dev Hub
                - script: |
                      echo "$(DEVHUB_SFDX_URL)" > DEVHUB_SFDX_URL.txt
                  displayName: 'Populate auth file with DEVHUB_SFDX_URL secret'
                - script: sf org login sfdx-url -f DEVHUB_SFDX_URL.txt -a devhub -d
                  displayName: 'Authenticate Dev Hub'

                # Step 3: Create a new package version
                - script: |
                      PACKAGE_VERSION_ID=$(sf package version create --package "yl-smon" --wait 10 -v sfprod --installation-key-bypass --code-coverage --json | jq -r '.result.SubscriberPackageVersionId')
                      echo "##vso[task.setvariable variable=PACKAGE_VERSION_ID]$PACKAGE_VERSION_ID"
                  displayName: 'Create Package Version and Set Variable'

                # Step 4: Authenticate with UAT
                - script: |
                      echo "$(UAT_SFDX_URL)" > UAT_SFDX_URL.txt
                  displayName: 'Populate auth file with UAT_SFDX_URL secret'
                - script: sf org login sfdx-url -f UAT_SFDX_URL.txt -a uat -d
                  displayName: 'Authenticate UAT'

                # Step 5: Install the package in UAT
                - script: |
                      sf package install --package "$(PACKAGE_VERSION_ID)" --target-org uat --apex-compile package --publish-wait 10 -w 10
                  displayName: 'Install Package in UAT'
